/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f429xx.h"


// Macros definition
/// Command codes
#define COMMAND_LED_CTRL    0x50
#define COMMAND_SENSOR_READ 0x51
#define COMMAND_LED_READ    0x52
#define COMMAND_PRINT       0x53
#define COMMAND_ID_READ     0x54
#define LED_ON  1
#define LED_OFF 0

//Arduino analog pins
#define ANALOG_PIN0     0
#define ANALOG_PIN1     1
#define ANALOG_PIN2     2
#define ANALOG_PIN3     3
#define ANALOG_PIN4     4

//Arduino led
#define LED_PIN         9

// delay API use for debouncing button
void delay(void)
{
  for(volatile uint32_t i = 0; i < 50000; i++);
}

// SPI6_NSS   -   PG8   -   AF05   ← now used for hardware CS
// SPI6_MISO  -   PG12  -   AF05
// SPI6_MOSI  -   PG14  -   AF05
// SPI6_CLK   -   PG13  -   AF05

void SPI6_GPIOInit(void)
{
	GPIO_Handle_t SPIPins;

	SPIPins.pGPIOx                        = GPIOG;
	SPIPins.GPIO_PinCFG.GPIO_PinMode      = GPIO_MODE_ALFN;
	SPIPins.GPIO_PinCFG.GPIO_PinSpeed     = GPIO_OUTPUT_HSPEED;
	SPIPins.GPIO_PinCFG.GPIO_PinPuPdCtrl  = GPIO_NO_PULL;
	SPIPins.GPIO_PinCFG.GPIO_PinOPType    = GPIO_OUTPUT_PP;
	SPIPins.GPIO_PinCFG.GPIO_PinAltMode   = 5;

	// CLK
	SPIPins.GPIO_PinCFG.GPIO_PinNumber    = GPIO_PIN_NO_13;
	GPIO_Init(&SPIPins);

	// MOSI
	SPIPins.GPIO_PinCFG.GPIO_PinNumber    = GPIO_PIN_NO_14;
	GPIO_Init(&SPIPins);

	// MISO
	SPIPins.GPIO_PinCFG.GPIO_PinNumber    = GPIO_PIN_NO_12;
	GPIO_Init(&SPIPins);

	// NSS - now enabled for hardware CS
	SPIPins.GPIO_PinCFG.GPIO_PinNumber    = GPIO_PIN_NO_8;
	GPIO_Init(&SPIPins);

/**
 * Simple analogy:
 * Imagine someone reading morse code:
 *
 * * Slave device = a morse code expert who starts fresh every time they hear a beep, always in sync
 * * Logic analyzer = a recorder that started recording late, doesn't know if it missed the first beep or not
 *
 * Bottom line:
 * The slave device's dedicated SPI hardware naturally syncs to CLK from the very first pulse.
 * The logic analyzer has no such intelligence — it needs CS to know exactly when transmission starts.
 *
 * */
}

void SPI6_Init(void)
{
	SPIx_Handle_t SPI6Handler;

	SPI6Handler.pSPIx                     = SPI6;
	SPI6Handler.SPIConfig.SPI_DeviceMode  = SPI_DEVICE_MODE_MASTER;
	SPI6Handler.SPIConfig.SPI_BusConfig   = SPI_BUS_CONFIG_FD;
	SPI6Handler.SPIConfig.SPI_SclkSpeed   = SPI_SCLK_SPEED_DIV8;
	SPI6Handler.SPIConfig.SPI_DFF         = SPI_DFF_8BITS;
	SPI6Handler.SPIConfig.SPI_CPOL        = SPI_CPOL_LOW;
	SPI6Handler.SPIConfig.SPI_CPHA        = SPI_CPHA_FIRST_CAPTURE;
	SPI6Handler.SPIConfig.SPI_SSM         = SPI_SSM_DIS;   // hardware NSS

	SPI_Init(&SPI6Handler);
}

void GPIO_ButtonInit(void)
{
	GPIO_Handle_t gpio_btn;

	gpio_btn.pGPIOx = GPIOB;
	gpio_btn.GPIO_PinCFG.GPIO_PinNumber = GPIO_PIN_NO_12;
	gpio_btn.GPIO_PinCFG.GPIO_PinMode = GPIO_MODE_INPUT;
	gpio_btn.GPIO_PinCFG.GPIO_PinSpeed = GPIO_OUTPUT_HSPEED;
	gpio_btn.GPIO_PinCFG.GPIO_PinPuPdCtrl = GPIO_PULL_UP;

	GPIO_PclkCtrl(GPIOB, ENABLE);

  GPIO_Init(&gpio_btn);
}

uint8_t SPI_VerifyResponse(uint8_t ackbyte)
{
    if(ackbyte == 0xff)
    {
        return 1;
    }
    return 0;
}

int main(void)
{

    SPI6_GPIOInit();
	SPI6_Init();
    GPIO_ButtonInit();

    uint8_t dummy_write = 255;
    uint8_t dummy_read;

    while(1)
    {
        if(!(GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_12)))
        {
        delay();

        if(!(GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_12)))
        {
            // SSOE = 1: NSS pulled low automatically when SPE=1
            SPI_SSOEConfig(SPI6, ENABLE);

            // Enable SPI — this also pulls NSS low automatically
            SPI_PeripheralControl(SPI6, ENABLE);

            // 1. CMD_LED_CTRL <pin no>     <value>
            uint8_t  ackbyte = 0;
            uint8_t  commandcode = COMMAND_LED_CTRL;
            uint8_t  args[2];
            SPI_SendData(SPI6, &commandcode,1);
            SPI_ReceiveData(SPI6, &dummy_read, 1);

            // Send some dummy bits (1 byte) to fetch the reponse from the slave
            SPI_SendData(SPI6, &dummy_write, 1);
            // Do dummy read to clear off the RXNE
            SPI_ReceiveData(SPI6, &ackbyte, 1);

            if(SPI_VerifyResponse(ackbyte))
            {
                args[0] = LED_PIN;
                args[1] = LED_ON;

                // Send arguments
                SPI_SendData(SPI6, args, 2);

            }

            // Disable SPI — this releases NSS high automatically
            SPI_PeripheralControl(SPI6, DISABLE);

            while(!(GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_12)));

            delay();
        }
        }
    }

        return 0;
}
