/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "stm32f429xx.h"


// delay API use for debouncing button
void delay(void)
{
  for(volatile uint32_t i = 0; i < 50000; i++);
}

// SPI6_NSS   -   PG8   -   AF05   ← now used for hardware CS
// SPI6_MISO  -   PG12  -   AF05
// SPI6_MOSI  -   PG14  -   AF05
// SPI6_CLK   -   PG13  -   AF05

void SPI6_GPIOInit(void)
{
	GPIO_Handle_t SPIPins;

	SPIPins.pGPIOx                        = GPIOG;
	SPIPins.GPIO_PinCFG.GPIO_PinMode      = GPIO_MODE_ALFN;
	SPIPins.GPIO_PinCFG.GPIO_PinSpeed     = GPIO_OUTPUT_HSPEED;
	SPIPins.GPIO_PinCFG.GPIO_PinPuPdCtrl  = GPIO_NO_PULL;
	SPIPins.GPIO_PinCFG.GPIO_PinOPType    = GPIO_OUTPUT_PP;
	SPIPins.GPIO_PinCFG.GPIO_PinAltMode   = 5;

	// CLK
	SPIPins.GPIO_PinCFG.GPIO_PinNumber    = GPIO_PIN_NO_13;
	GPIO_Init(&SPIPins);

	// MOSI
	SPIPins.GPIO_PinCFG.GPIO_PinNumber    = GPIO_PIN_NO_14;
	GPIO_Init(&SPIPins);

	// MISO
	SPIPins.GPIO_PinCFG.GPIO_PinNumber    = GPIO_PIN_NO_12;
	GPIO_Init(&SPIPins);

	// NSS - now enabled for hardware CS
	SPIPins.GPIO_PinCFG.GPIO_PinNumber    = GPIO_PIN_NO_8;
	GPIO_Init(&SPIPins);

/**
 * Simple analogy:
 * Imagine someone reading morse code:
 *
 * * Slave device = a morse code expert who starts fresh every time they hear a beep, always in sync
 * * Logic analyzer = a recorder that started recording late, doesn't know if it missed the first beep or not
 *
 * Bottom line:
 * The slave device's dedicated SPI hardware naturally syncs to CLK from the very first pulse.
 * The logic analyzer has no such intelligence — it needs CS to know exactly when transmission starts.
 *
 * */
}

void SPI6_Init(void)
{
	SPIx_Handle_t SPI6Handler;

	SPI6Handler.pSPIx                     = SPI6;
	SPI6Handler.SPIConfig.SPI_DeviceMode  = SPI_DEVICE_MODE_MASTER;
	SPI6Handler.SPIConfig.SPI_BusConfig   = SPI_BUS_CONFIG_FD;
	SPI6Handler.SPIConfig.SPI_SclkSpeed   = SPI_SCLK_SPEED_DIV8;
	SPI6Handler.SPIConfig.SPI_DFF         = SPI_DFF_8BITS;
	SPI6Handler.SPIConfig.SPI_CPOL        = SPI_CPOL_LOW;
	SPI6Handler.SPIConfig.SPI_CPHA        = SPI_CPHA_FIRST_CAPTURE;
	SPI6Handler.SPIConfig.SPI_SSM         = SPI_SSM_DIS;   // hardware NSS

	SPI_Init(&SPI6Handler);
}

void GPIO_ButtonInit(void)
{
	GPIO_Handle_t gpio_btn;

	gpio_btn.pGPIOx = GPIOB;
	gpio_btn.GPIO_PinCFG.GPIO_PinNumber = GPIO_PIN_NO_12;
	gpio_btn.GPIO_PinCFG.GPIO_PinMode = GPIO_MODE_INPUT;
	gpio_btn.GPIO_PinCFG.GPIO_PinSpeed = GPIO_OUTPUT_HSPEED;
	gpio_btn.GPIO_PinCFG.GPIO_PinPuPdCtrl = GPIO_PULL_UP;

	GPIO_PclkCtrl(GPIOB, ENABLE);

  GPIO_Init(&gpio_btn);
}

int main(void)
{
	char user_data[] = "Hello World";

	SPI6_GPIOInit();
	SPI6_Init();
  GPIO_ButtonInit();

  while(1)
  {
    if(!(GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_12)))
    {
      delay();

      if(!(GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_12)))
      {
        // SSOE = 1: NSS pulled low automatically when SPE=1
        SPI_SSOEConfig(SPI6, ENABLE);

        // Enable SPI — this also pulls NSS low automatically
        SPI_PeripheralControl(SPI6, ENABLE);

        uint8_t dataLen = strlen(user_data);

        SPI_SendData(SPI6, &dataLen, 1);

        for(volatile uint32_t i = 0; i < 100; i++);

        SPI_SendData(SPI6, (uint8_t *)user_data, strlen(user_data));

        // Disable SPI — this releases NSS high automatically
        SPI_PeripheralControl(SPI6, DISABLE);

        while(!(GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_12)));

        delay();
      }
    }
  }

	return 0;
}
